### ISSUE TITLE
fab stage should create a zip of the distribution

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/fablib#1]
I realize that because our CDN isn't browsable and we no longer offer the `build` directory, it's not extremely straightforward to download a TimelineJS (or other) distribution to run on a separate server.

We should modify the `fab stage` command to also drop a ZIP file in the CDN directory where other assets are placed. Ideally when unpacked it would create a directory with the project name (e.g. `timelinejs3` or `storymapjs`) whose contents are the same as the versioned directory on the CDN. After it's created, it should be available alongside the other assets, e.g. at `https://cdn.knightlab.com/libs/timeline3/latest/timeline3.zip`

**Comment by jywsn** [comment]
8aa86cd86e2cb11dea915730475ab726d3f7b6e9

Zip file creation will happen during `stage` and `stage_dev`.  `stage_latest` will obviously just copy whatever is in the versioned directory (which would include any zip file).
